### ISSUE TITLE
Ability to configure without using a file

### ISSUE THREAD

**Issue by ak4noir** [snipermonke01/gmx_python_sdk#17]
I'm looking to incorporate this with something that I am building. One thing I've noticed is that there doesn't seem to be another way to configure the SDK without there being a config file present. 

As my project already has it's own way of handling configuration, having an extra file to have to maintain just to use this code is rather cumbersome, and has lead me to try my hand at an SDK, but ultimately that is silly.

I have a few ideas I'd like to propose that I think would make this easier to integrate into other projects.

As a potential low-effort first step, what would you think about getting the config values from environment variables if a file doesn't exist?

Another option is to create a wrapper client that handles configuration, and acts as a entrypoint for the rest of the methods here. This gives the user absolute freedom on how the SDK is configured and this is what my iteration of the SDK does, which is  just a fork of [dydx-v3-python](https://github.com/dydxprotocol/dydx-v3-python).

e.g.

```python
from gmx.v2 import GmxClient
from gmx.v2 import constants

ACCOUNT = "0x000"

gmx = GmxClient(account=ACCOUNT, rpc_url=constants.ARBITRUM_RPC_URL)

gmx.create_order(market, size, market_position)
```

What are your thoughts on this?

**Comment by snipermonke01** [comment]
Hey sorry just seen you open this. There is a new development pending currently sitting on staging that will address this point of feedback

https://github.com/snipermonke01/gmx_python_sdk/blob/staging/gmx_python_sdk/scripts/v2/gmx_utils.py#L143
