### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by chris-anjost** [snipermonke01/gmx_python_sdk#25]
Hi there,

since you introduced the `GetData` abstraction, the stats collector will write to the same file ending `_data.csv` - thereby mixing different  metrics e.g. open interest, funding fee etc. The file name is fixed. Just like with `_get_data_processing`, you could provide a function to override which actually sets the file name or suffix for the metric in question.

Furthermore, the transformation from your raw data dict to a pandas data frame needs to be revisited as well. The format is not quite correct and most data columns will be discarded.

I also need to emphasise at this point that I am thankful that you are working on a SDK for GMX! Good stuff!

**Comment by snipermonke01** [comment]
Thank you for raising, will get it fixed asap
