### ISSUE TITLE
What does this code mean?

### ISSUE THREAD

**Issue by SilkageNet** [snipermonke01/gmx_python_sdk#30]
https://github.com/snipermonke01/gmx_python_sdk/blob/49dc0fd18b30d3646ad0828f2b1387951cab8e99/gmx_python_sdk/scripts/v2/get/get_open_interest.py#L77-L78

```python
 oracle_factor = (30 - decimal_factor) 
 precision = 10 ** (decimal_factor + oracle_factor) 

 precision = 10 ** (decimal_factor + 30 - decimal_factor) 

 precision = 10 ** 30 
``` 

Isn't the value of `precision` always equal to `10 ** 30` ?

**Comment by snipermonke01** [comment]
Yes, likely just a misnomer. You are correct, precision in the traditional sense ie conversion from a big int is always 10 ** 30
