### ISSUE TITLE
2.1 contract version breaking change

### ISSUE THREAD

**Issue by using-system** [snipermonke01/gmx_python_sdk#31]
Since 2.1 contract version,

All transaction on gmx exchange route on arbitrum are failed : https://arbiscan.io/address/0x7c68c7866a64fa2160f78eeae12217ffbf871fa8

Can you fix it ?

Many thanks.

**Comment by snipermonke01** [comment]
Pushed latest branch

Testing is ongoing and will merged through to main with the new deployment of the pip package in the next few days

Thanks

**Comment by using-system** [comment]
I use the package referenced here https://pypi.org/project/gmx-python-sdk/#history

Tell us when it will be updated.

Many thanks.
