### ISSUE TITLE
the stats_object.get_gm_price() get eth/usd price is wrong

### ISSUE THREAD

**Issue by elevenWANG112** [snipermonke01/gmx_python_sdk#33]
the stats_object.get_gm_price() get eth/usd price is wrong

{'long': {}, 'short': {}, 'BTC': 1.7421649127985883, 'ETH': 1.0012161671927986,)

**Comment by snipermonke01** [comment]
I believe there is a problem with the new wstETH pools overwriting the values for existing gmETH price. Will incl a fix in the next release.

**Comment by snipermonke01** [comment]
this should now be fixed when the latest merge to main occurs

https://github.com/snipermonke01/gmx_python_sdk/compare/0adae0f3fcde316ea2a88dcfd973b615f5b1be32...1c2051902fb2ebd2f8975adbe72bdce59769d664
