### ISSUE TITLE
Addresses from contract_map: where did you find them?

### ISSUE THREAD

**Issue by francestu96** [snipermonke01/gmx_python_sdk#37]
Hello, I was wondering where did you find the contract addresses of the **contract_map** dict?

From the GMX official doc I cannot find any reference to those addresses...

**Comment by snipermonke01** [comment]
You can find them on the GMX Interface Github repo

Arbitrum: https://github.com/gmx-io/gmx-interface/blob/master/src/config/contracts.ts#L181-L193

Avalanche: https://github.com/gmx-io/gmx-interface/blob/master/src/config/contracts.ts#L239-L251
