### ISSUE TITLE
Trade with BTC not working

### ISSUE THREAD

**Issue by francestu96** [snipermonke01/gmx_python_sdk#41]
This config will raise an exception:

```
parameters = {
    "chain": 'arbitrum',

    # the market you want to trade on
    "index_token_symbol": "BTC",

    # token to use as collateral. Start token swaps into collateral token
    # if different
    "collateral_token_symbol": "BTC",

    # the token to start with - WETH not supported yet
    "start_token_symbol": "USDC",

    # True for long, False for short
    "is_long": False,

    # Position size in in USD
    "size_delta_usd": 5,

    # if leverage is passed, will calculate number of tokens in
    # start_token_symbol amount
    "leverage": 1,

    # as a decimal ie 0.003 == 0.3%
    "slippage_percent": 0.003
}
```
By set **index_token_symbol** and **collateral_token_symbol** as **BTC** it will not be able to find the index_token_address in function **find_dictionary_by_key_value()** at line **756 in gmx_utils.py**.

I think the problem born in **_process_markets()** function. It looks like to me there is a discrepancy between the markets data from the **API** and what **DataStore** contract returns.

What is quite weird to me, is that the first DataStore record is like this:
`('0x47c031236e19d024b42f8AE6780E44A573170703', '0x47904963fc8b2340414262125aF798B9655E58Cd', '0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f', '0xaf88d065e77c8cC2239327C5EDb3A432268e5831')`

To match the doc info we get:
marketToken: [0x47c031236e19d024b42f8AE6780E44A573170703](https://arbiscan.io/address/0x47c031236e19d024b42f8AE6780E44A573170703)
indexToken: [0x47904963fc8b2340414262125aF798B9655E58Cd](https://arbiscan.io/address/0x47904963fc8b2340414262125aF798B9655E58Cd)
longToken: [0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f](https://arbiscan.io/address/0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f)
shortToken: [0xaf88d065e77c8cC2239327C5EDb3A432268e5831](https://arbiscan.io/address/0xaf88d065e77c8cC2239327C5EDb3A432268e5831)

This address is quite suspicious: **0x47904963fc8b2340414262125aF798B9655E58Cd**
It is supposed to be the WBTC address but it's not. 

I don't know why but it looks like DataStore and API are mixing BTC and WBTC.b address...
Btw, **0x47904963fc8b2340414262125aF798B9655E58Cd** this is definitely a weird address.
 
Can you try it?
Thank you

**Comment by snipermonke01** [comment]
I will investigate and get it fixed, i was waiting for the tBTC market to launch (and i has today) before i worked on and implemented any fixes

**Comment by snipermonke01** [comment]
regarding the CA: 0x47904963fc8b2340414262125aF798B9655E58Cd i will speak to the contributors and determine the reason for this

**Comment by miamiappmachine** [comment]
Any updates on the contract address here?

**Comment by snipermonke01** [comment]
This bug has been patched in latest merge from staging

https://github.com/snipermonke01/gmx_python_sdk/activity?ref=41-trade-with-btc-not-working

**Comment by miamiappmachine** [comment]
> This bug has been patched in latest merge from staging
> 
> https://github.com/snipermonke01/gmx_python_sdk/activity?ref=41-trade-with-btc-not-working

@snipermonke01  - is the contract address  0x47904963fc8b2340414262125aF798B9655E58Cd still used anywhere? And if so, is it legitimate?

**Comment by snipermonke01** [comment]
Yes it is a legitimate contract address. It is a synthetic token as there is no token address for BTC on arbitrum as it does not exist.

**Comment by miamiappmachine** [comment]
Excellent, thank you!
