### ISSUE TITLE
how can i get the Composition percent of gm

### ISSUE THREAD

**Issue by elevenWANG112** [snipermonke01/gmx_python_sdk#42]

**Comment by snipermonke01** [comment]
within GLV? or the tokens that make up a given GM?

**Comment by elevenWANG112** [comment]
The tokens that make up a given GM

**Comment by snipermonke01** [comment]
https://github.com/snipermonke01/gmx_python_sdk/blob/main/gmx_python_sdk/scripts/v2/get/get_pool_tvl.py

i believe this script is what you are looking for
