### ISSUE TITLE
TypeError: BaseContract.encodeABI() is not a function

### ISSUE THREAD

**Issue by francestu96** [snipermonke01/gmx_python_sdk#49]
In **gmx_python_sdk\scripts\v2\order\order.py** you are using the **encodeABI** function but I got an error on that function.

On the project requirements it's set **web3 = ">= 6.10.0"**.
It installed on my machine **web3==7.2.0** and it looks like the function has been replaced.

Could you update and fix with the new **web3** version?

**Comment by snipermonke01** [comment]
This has been fixed, thank you again for raising.

https://github.com/snipermonke01/gmx_python_sdk/commit/aa2b698975b295cea02a316edf4f7b8e76c0cbd0
