### ISSUE TITLE
Get Positions not working on TONCoin for Arbitrum

### ISSUE THREAD

**Issue by crypto-rizzo** [snipermonke01/gmx_python_sdk#57]
`ERROR: Incompatible market: '0x15c6eBD4175ffF9EE3c2615c556fCf62D2d9499c'`

Can't find where this `0x...99c` comes from, but if you run 
https://arbiscan.io/address/0x0537C767cDAC0726c76Bb89e92904fe28fd02fE1#readContract#F8 with these arguments:

Data Store:
0xFD70de6b91282D8017aA4E741e9Ae325CAb992d8

Key:
0x15c6eBD4175ffF9EE3c2615c556fCf62D2d9499c

You get the correct address in the tuple at 0xB2f7cefaeEb08Aa347705ac829a7b8bE2FB560f3

**Comment by crypto-rizzo** [comment]
🤦 Missed this commit: https://github.com/snipermonke01/gmx_python_sdk/pull/56/files

**Comment by snipermonke01** [comment]
No worries, it’s not been merged through main branch just yet just fyi, and will require another tweak as more markets have been added.

will alter and merge through to main today with a new pip version
